### ISSUE TITLE
Issue with output

### ISSUE THREAD

**Issue by overthink** [martende/sortable#1]
Hi there.

Thanks for trying our challenge.  There is a problem with the output format that is preventing me from scoring your solution.  Could you please make sure the listings in the output are exactly the same as the listings in listings.txt?

e.g.

in listings.txt:

`{"title":"Nikon D7000 Digital SLR Body Only Taxes Included!","manufacturer":"Nikon","currency":"CAD","price":"1419.95"}`

in result.txt from your solution:

`... {"currency": "CAD", "price": "1419.95", "manufacturer": "nikon", "title": "nikon d7000 digital slr body only taxes included!"} ...` (manufacturer and title have been lowercased)

Thanks,

Mark (from sortable.com)

**Comment by martende** [comment]
ops got it , fixed in 065fd5e72536b64cf952a64acb3b79e01901177f

**Comment by overthink** [comment]
Thanks for the quick fix.
